import { auth, db, OWNER_EMAIL } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { collection, deleteDoc, doc, getDoc, getDocs, query, serverTimestamp, setDoc, updateDoc, where } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const $ = (id) => document.getElementById(id);
const esc = (value = '') => String(value).replace(/[&<>"']/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[char]);
const emailKey = (value = '') => String(value).trim().toLowerCase();
const mirrorId = (assessmentId) => `grade_assessment_${assessmentId}`;
let profile = null, courses = [], currentCourse = null, assignments = [], assessments = [], submissions = [], attempts = [], students = [];
let selectedCourseId = localStorage.getItem('classos-gradebook-course') || '', rendering = false, timer = null;
const uid = () => auth.currentUser?.uid || '';
const role = () => profile?.role || '';
const isOwner = () => emailKey(auth.currentUser?.email) === OWNER_EMAIL;
const canEdit = () => isOwner() || ['district_admin','school_admin','teacher'].includes(role());

function toast(message, type='') { const host=$('toast-region'); if(!host)return; const n=document.createElement('div'); n.className=`toast ${type}`.trim(); n.textContent=message; host.appendChild(n); setTimeout(()=>n.remove(),4200); }
async function direct(name,id){const s=await getDoc(doc(db,name,id));return s.exists()?{id:s.id,...s.data()}:null;}
async function byField(name,field,value){const s=await getDocs(query(collection(db,name),where(field,'==',value)));return s.docs.map(d=>({id:d.id,...d.data()}));}
async function arrayContains(name,field,value){const s=await getDocs(query(collection(db,name),where(field,'array-contains',value)));return s.docs.map(d=>({id:d.id,...d.data()}));}
function unique(items){const m=new Map();items.forEach(i=>i?.id&&m.set(i.id,i));return [...m.values()];}
async function loadProfile(){return auth.currentUser?direct('users',auth.currentUser.uid):null;}
async function loadCourses(){
  if(isOwner()){const s=await getDocs(collection(db,'courses'));return s.docs.map(d=>({id:d.id,...d.data()})).filter(c=>c.status!=='archived');}
  if(role()==='teacher')return (await arrayContains('courses','teacherIds',uid())).filter(c=>c.status!=='archived');
  if(['district_admin','school_admin'].includes(role())){const batches=await Promise.all((profile?.schoolIds||[]).map(id=>byField('courses','schoolId',id)));return unique(batches.flat()).filter(c=>c.status!=='archived');}
  return [];
}
async function person(id){try{return await direct('users',id)||{id,displayName:'Student'};}catch{return{id,displayName:'Student'};}}
function categories(){return Array.isArray(currentCourse?.gradeCategories)&&currentCourse.gradeCategories.length?currentCourse.gradeCategories.map(c=>({id:String(c.id||'coursework'),name:String(c.name||'Coursework'),weight:Number(c.weight)||0})):[{id:'coursework',name:'Coursework',weight:100}];}
function gradeItems(){
  const a=assignments.map(x=>({id:x.id,type:'assignment',title:x.title,pointsPossible:Number(x.pointsPossible)||0,categoryId:x.categoryId||'coursework',dueAt:x.dueAt}));
  const q=assessments.map(x=>({id:x.id,type:'assessment',title:x.title,pointsPossible:Number(x.pointsPossible)||0,categoryId:x.categoryId||'coursework',dueAt:x.dueAt}));
  return a.concat(q).sort((x,y)=>(Number(x.dueAt?.seconds||0)-Number(y.dueAt?.seconds||0))||String(x.title).localeCompare(String(y.title)));
}
function submissionFor(id,studentId){return submissions.find(s=>s.assignmentId===id&&s.studentId===studentId)||null;}
function attemptFor(id,studentId){return attempts.find(a=>a.assessmentId===id&&a.studentId===studentId)||null;}
function assessmentRecord(item,studentId){return attemptFor(item.id,studentId)||submissionFor(mirrorId(item.id),studentId);}
function recordFor(item,studentId){return item.type==='assessment'?assessmentRecord(item,studentId):submissionFor(item.id,studentId);}
function overall(studentId){
  const items=gradeItems(); const cats=categories().map(c=>{let earned=0,possible=0;items.filter(i=>i.categoryId===c.id).forEach(i=>{const r=recordFor(i,studentId);if(r?.status==='graded'&&Number.isFinite(Number(r.score))){earned+=Number(r.score);possible+=i.pointsPossible;}});return{...c,earned,possible,percent:possible?earned/possible*100:null};});
  const active=cats.filter(c=>c.percent!==null&&c.weight>0),w=active.reduce((s,c)=>s+c.weight,0);if(active.length&&w)return active.reduce((s,c)=>s+c.percent*c.weight/w,0);const e=cats.reduce((s,c)=>s+c.earned,0),p=cats.reduce((s,c)=>s+c.possible,0);return p?e/p*100:null;
}
function gradeLabel(v){return v===null||!Number.isFinite(v)?'—':`${v.toFixed(1)}%`;}
function letter(v){if(v===null||!Number.isFinite(v))return'—';return v>=90?'A':v>=80?'B':v>=70?'C':v>=60?'D':'F';}
function cellValue(r){if(!r)return'';if(r.status==='graded'&&r.score!==null&&r.score!==undefined)return String(r.score);if(r.status==='missing')return'M';if(r.status==='excused')return'EX';return'';}
function cellClass(v){const u=String(v||'').trim().toUpperCase();return u==='M'?' is-missing':u==='EX'?' is-excused':'';}

async function loadCourse(courseId){
  currentCourse=courses.find(c=>c.id===courseId)||null;if(!currentCourse)return;
  const [a,q,s,t]=await Promise.all([byField('assignments','courseId',courseId),byField('assessments','courseId',courseId),byField('submissions','courseId',courseId),byField('assessmentAttempts','courseId',courseId)]);
  assignments=a.filter(x=>x.status!=='draft'&&!x.sourceAssessmentId&&Number(x.pointsPossible)>0); assessments=q.filter(x=>x.status==='published'&&Number(x.pointsPossible)>0); submissions=s; attempts=t;
  students=await Promise.all((currentCourse.studentIds||[]).map(person)); students.sort((x,y)=>String(x.displayName||x.email||'').localeCompare(String(y.displayName||y.email||'')));
}
function courseOptions(){return courses.map(c=>`<option value="${esc(c.id)}" ${c.id===selectedCourseId?'selected':''}>${esc(c.name||'Course')}${c.courseCode?` (${esc(c.courseCode)})`:''}</option>`).join('');}
function table(){
  const items=gradeItems(); if(!students.length)return'<div class="empty-state"><strong>No students are rostered.</strong>Add students to this course before entering grades.</div>'; if(!items.length)return'<div class="empty-state"><strong>No graded work yet.</strong>Create an assignment or publish an assessment with points.</div>';
  const heads=items.map(i=>`<th class="gb-assignment-head"><span>${esc(i.title)}</span><small><b class="gb-type ${i.type}">${i.type==='assessment'?'Assessment':'Assignment'}</b>${i.pointsPossible} pts</small></th>`).join('');
  const rows=students.map(st=>{const cells=items.map(i=>{const r=recordFor(i,st.id),v=cellValue(r);return`<td class="gb-grade-cell"><input class="gb-grade-input${cellClass(v)}" value="${esc(v)}" data-student-id="${esc(st.id)}" data-item-id="${esc(i.id)}" data-item-type="${i.type}" data-initial="${esc(v)}" inputmode="decimal" autocomplete="off"></td>`;}).join('');const g=overall(st.id);return`<tr><td class="gb-student"><strong>${esc(st.displayName||st.email||'Student')}</strong><small>${esc(st.email||'')}</small></td><td class="gb-overall"><strong>${esc(gradeLabel(g))}</strong><small>${letter(g)}</small></td>${cells}</tr>`;}).join('');
  return`<div class="gb-table-wrap"><table class="gb-table"><thead><tr><th class="gb-student">Student</th><th class="gb-overall">Overall</th>${heads}</tr></thead><tbody>${rows}</tbody></table></div>`;
}
function renderPage(){
  const content=$('page-content');if(!content||$('page-title')?.textContent!=='Gradebook'||!canEdit())return;const items=gradeItems(),graded=students.reduce((n,s)=>n+items.filter(i=>recordFor(i,s.id)?.status==='graded').length,0),open=students.length*items.length-graded;
  content.innerHTML=`<div class="gradebook-plus"><div class="toolbar gb-toolbar"><div><span class="eyebrow">GRADEBOOK</span><h2>${esc(currentCourse?.name||'Gradebook')}</h2><p>Enter assignment and assessment grades for the whole class from one screen.</p></div><div class="toolbar-group"><button class="btn btn-secondary" data-lms-action="new-assignment" data-course-id="${esc(currentCourse?.id||'')}">New Assignment</button><button class="btn btn-secondary" data-p3-nav="assessments">Assessments</button><button class="btn btn-primary" data-gb-action="save">Save Changes</button></div></div><section class="gb-course-bar"><label>Course<select id="gb-course-select">${courseOptions()}</select></label><div class="gb-legend"><span><b>Number</b> grade</span><span><b>M</b> missing</span><span><b>EX</b> excused</span><span><b>Blank</b> not graded</span></div></section><section class="grid grid-3 section gb-summary"><article class="card metric"><div class="metric-top"><span>Students</span></div><div class="metric-value">${students.length}</div><div class="metric-note">Rostered in this course</div></article><article class="card metric"><div class="metric-top"><span>Grade items</span></div><div class="metric-value">${items.length}</div><div class="metric-note">${assignments.length} assignments · ${assessments.length} assessments</div></article><article class="card metric"><div class="metric-top"><span>Open cells</span></div><div class="metric-value">${Math.max(0,open)}</div><div class="metric-note">Not currently graded</div></article></section><section class="section">${table()}</section><div class="gb-save-bar"><span id="gb-save-status">No unsaved changes</span><button class="btn btn-primary" data-gb-action="save">Save Changes</button></div></div>`;
}
async function renderGradebook(requested=selectedCourseId){if(rendering||$('page-title')?.textContent!=='Gradebook'||!canEdit())return;const content=$('page-content');if(!content)return;rendering=true;content.innerHTML='<div class="skeleton" style="height:180px"></div>';try{courses=await loadCourses();if(!courses.length){content.innerHTML='<div class="empty-state"><strong>No courses available.</strong>Create or join a course before using the gradebook.</div>';return;}selectedCourseId=courses.some(c=>c.id===requested)?requested:courses[0].id;localStorage.setItem('classos-gradebook-course',selectedCourseId);await loadCourse(selectedCourseId);renderPage();}catch(e){console.error(e);content.innerHTML=`<div class="empty-state"><strong>Gradebook could not load.</strong>${esc(e.message||'')}</div>`;}finally{rendering=false;}}
function parse(v){const raw=String(v||'').trim(),u=raw.toUpperCase();if(!raw)return{type:'clear'};if(u==='M')return{type:'missing'};if(u==='EX'||u==='E')return{type:'excused'};const score=Number(raw);if(!Number.isFinite(score)||score<0)throw new Error(`“${raw}” is not a valid grade.`);return{type:'grade',score};}
async function saveAssignment(item,studentId,p){const existing=submissionFor(item.id,studentId),id=existing?.id||`${item.id}_${studentId}`,ref=doc(db,'submissions',id);if(p.type==='clear'){if(!existing)return;const work=String(existing.responseText||'').trim()||String(existing.linkUrl||'').trim()||existing.submittedAt;if(!work)return deleteDoc(ref);return setDoc(ref,{score:null,status:'submitted',gradedBy:null,gradedAt:null,updatedAt:serverTimestamp()},{merge:true});}const base={assignmentId:item.id,courseId:currentCourse.id,schoolId:currentCourse.schoolId,studentId,responseText:existing?.responseText||'',linkUrl:existing?.linkUrl||'',feedback:existing?.feedback||'',submittedAt:existing?.submittedAt||null,updatedAt:serverTimestamp()};if(p.type==='grade')return setDoc(ref,{...base,status:'graded',score:p.score,gradedBy:uid(),gradedAt:serverTimestamp()},{merge:true});return setDoc(ref,{...base,status:p.type,score:null,gradedBy:uid(),gradedAt:serverTimestamp()},{merge:true});}
async function ensureAssessmentMirror(item){const id=mirrorId(item.id),ref=doc(db,'assignments',id),snap=await getDoc(ref);if(!snap.exists())await setDoc(ref,{organizationId:currentCourse.organizationId||'',schoolId:currentCourse.schoolId,courseId:currentCourse.id,title:item.title,categoryId:item.categoryId||'coursework',categoryName:categories().find(c=>c.id===(item.categoryId||'coursework'))?.name||'Coursework',pointsPossible:item.pointsPossible,dueAt:item.dueAt||null,status:'draft',submissionType:'none',sourceAssessmentId:item.id,createdBy:uid(),teacherIds:currentCourse.teacherIds||[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return id;}
async function saveAssessment(item,studentId,p){const attempt=attemptFor(item.id,studentId);if(attempt){const ref=doc(db,'assessmentAttempts',attempt.id);if(p.type==='clear')return updateDoc(ref,{score:null,status:'submitted',gradedBy:null,gradedAt:null,updatedAt:serverTimestamp()});if(p.type==='grade')return updateDoc(ref,{score:p.score,status:'graded',gradedBy:uid(),gradedAt:serverTimestamp(),updatedAt:serverTimestamp()});return updateDoc(ref,{score:null,status:p.type,gradedBy:uid(),gradedAt:serverTimestamp(),updatedAt:serverTimestamp()});}const aid=await ensureAssessmentMirror(item),existing=submissionFor(aid,studentId),ref=doc(db,'submissions',existing?.id||`${aid}_${studentId}`);if(p.type==='clear'){if(existing)return deleteDoc(ref);return;}const base={assignmentId:aid,courseId:currentCourse.id,schoolId:currentCourse.schoolId,studentId,responseText:'',linkUrl:'',feedback:'',submittedAt:null,sourceAssessmentId:item.id,updatedAt:serverTimestamp()};if(p.type==='grade')return setDoc(ref,{...base,status:'graded',score:p.score,gradedBy:uid(),gradedAt:serverTimestamp(),createdAt:existing?.createdAt||serverTimestamp()},{merge:true});return setDoc(ref,{...base,status:p.type,score:null,gradedBy:uid(),gradedAt:serverTimestamp(),createdAt:existing?.createdAt||serverTimestamp()},{merge:true});}
async function saveCell(input){const item=gradeItems().find(i=>i.id===input.dataset.itemId&&i.type===input.dataset.itemType);if(!item)return;const p=parse(input.value);if(p.type==='grade'&&p.score>item.pointsPossible)throw new Error(`${item.title} is worth ${item.pointsPossible} points.`);return item.type==='assessment'?saveAssessment(item,input.dataset.studentId,p):saveAssignment(item,input.dataset.studentId,p);}
async function saveChanges(){const dirty=[...document.querySelectorAll('.gb-grade-input.is-dirty')];if(!dirty.length)return toast('There are no grade changes to save.');const buttons=[...document.querySelectorAll('[data-gb-action="save"]')];buttons.forEach(b=>{b.disabled=true;b.dataset.old=b.textContent;b.textContent='Saving…';});try{for(const i of dirty)await saveCell(i);toast(`${dirty.length} grade change${dirty.length===1?'':'s'} saved.`,'success');await renderGradebook(selectedCourseId);}catch(e){console.error(e);toast(e?.code==='permission-denied'?'Your account does not have permission to save one of these grades.':e.message||'Grades could not be saved.','error');}finally{buttons.forEach(b=>{if(document.body.contains(b)){b.disabled=false;b.textContent=b.dataset.old||'Save Changes';}});}}
function dirty(input){const v=input.value.trim();input.classList.toggle('is-dirty',v!==String(input.dataset.initial||'').trim());input.classList.remove('is-missing','is-excused');input.classList.add(...cellClass(v).trim().split(/\s+/).filter(Boolean));const n=document.querySelectorAll('.gb-grade-input.is-dirty').length;if($('gb-save-status'))$('gb-save-status').textContent=n?`${n} unsaved change${n===1?'':'s'}`:'No unsaved changes';}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>{if($('page-title')?.textContent==='Gradebook'&&!document.querySelector('#page-content .gradebook-plus')&&canEdit())renderGradebook().catch(console.error);},90);}
document.addEventListener('input',e=>{if(e.target.matches('.gb-grade-input'))dirty(e.target);},true);
document.addEventListener('change',e=>{if(e.target.id==='gb-course-select')renderGradebook(e.target.value);},true);
document.addEventListener('click',e=>{if(e.target.closest('[data-gb-action="save"]')){e.preventDefault();e.stopImmediatePropagation();saveChanges();return;}if(e.target.closest('[data-route="gradebook"],[data-lms-route="gradebook"],[data-lms-nav="gradebook"]'))setTimeout(schedule,120);},true);
if($('page-content'))new MutationObserver(schedule).observe($('page-content'),{childList:true,subtree:false});
onAuthStateChanged(auth,async user=>{if(!user){profile=null;courses=[];return;}try{profile=await loadProfile();schedule();}catch(e){console.warn('Gradebook could not initialize',e);}});
